#!/bin/bash


/usr/bin/pacman-bin $@

if [ $? -eq 0 ] && [ $EUID -eq 0 ] && [[ "$@" != *"--noconfirm"* ]]; then
   if [[ "$@" == *-S* ]] || [[ "$@" == *-U* ]]; then
	echo ""
	echo ":: Checking for pac files..."

	FILES="$(find /boot /etc -name '*.pacnew' -o -name '*.pacsave' | sort)"

	if [ "$FILES" != "" ]; then
		for file in $FILES; do
			echo " $file"
		done

		echo ""
		echo -ne "Start dotpac to handle files? [y/N] "
		read answer

		if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
			exit 0
		fi

		/usr/bin/dotpac
	fi
   fi
fi

