EXTRAMODULES='extramodules-3.2-MANJARO'
VERSION='linux32'

post_install() {
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo "vboxdrv" > /etc/modules-load.d/$VERSION-nvidiabl.conf
}

post_upgrade() {
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo "vboxdrv" > /etc/modules-load.d/$VERSION-nvidiabl.conf
}


post_remove() {
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    rm /etc/modules-load.d/$VERSION-nvidiabl.conf
}
